name: Teste

on: [push, workflow_dispatch]
jobs:
    teste:
        uses: LucasRius/lrios-ci-complete/.github/workflows/ci.yml@main
        with:
            language: 'scala'
            build_tool: 'sbt'
            toogle_lint_bypass: true