name: Teste

on: [push, workflow_dispatch]
jobs:
    teste:
        uses: LucasRius/lrios-ci-complete/.github/workflows/ci.yml@main
        with:
            language: 'scala'
            build_tool: 'sbt'
            toogle_lint_bypass: true
            lint_pre_hook: | 
              echo "TESTE 1"
              echo "TESTE 2"
            lint_post_hook: |
              echo "POST 1"
              echo "POST 2"